general.import = [
  "~/.config/alacritty/cyberdream.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12

[window]
padding = { x = 5, y = 5 }

[terminal]
shell = "zsh"

[cursor]
style = { shape = "Block" }

[keyboard]
bindings = [{ key = "Enter", mods = "Super | Shift", command = "alacritty" }]
