-- local now = Config.now
--
-- now(function()
--   vim.pack.add { 'https://github.com/catppuccin/nvim' }
--
--   require('catppuccin').setup {
--     no_italic = true,
--     color_overrides = {
--       mocha = {},
--     },
--   }
--   vim.cmd.colorscheme 'catppuccin'
-- end)
