backend = "glx";

shadow-radius = 16;
shadow-offset-x = -16;
shadow-offset-y = -16;

rules = (
    { match = "window_type = 'normal' && (focused || group_focused)"; dim = 0; shadow = true; },
    { match = "window_type = 'normal' && (!focused && !group_focused)"; dim = 0.2; shadow = false; },
    { match = "name *?= 'rofi'"; dim = 0; },
    { match = "class_g *?= 'awesome'"; dim = 0; }
);
