backend = "glx"
shadow-radius = 16
shadow-offset-x = -16
shadow-offset-y = -16
rules = (
    { match = "window_type = 'normal'"; shadow = true; dim = 0.2; },
    { match = "focused || group_focused"; dim = 0; },
    { match = "name *?= 'rofi'"; dim = 0; }
)
