backend = "glx";

animations = (
  {
    triggers = ["close"];
    preset = "disappear";
    duration = 0.1;
  },
  {
    triggers = ["open"];
    preset = "appear";
    duration = 0.1;
  },
  {
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.1;
  }
);

rules = (
    { match = "window_type = 'normal'"; },
    { match = "window_type = 'normal' && (focused || group_focused)"; dim = 0; },
    { match = "window_type = 'normal' && (!focused && !group_focused)"; dim = 0.2; },
    { match = "name *?= 'rofi'"; dim = 0; },
    { match = "class_g *?= 'awesome'"; dim = 0; }
);
