font=monospace:size=15
font-size-adjustment=1
box-drawings-uses-font-glyphs=no
dpi-aware=no

resize-delay-ms=0

word-delimiters=,│`|:"'()[]{}<>
selection-target=primary

initial-color-theme=dark
bold-text-in-bright=yes

[bell]
urgent=no
notify=no
visual=no

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

[cursor]
style=block
blink=no

[key-bindings]
spawn-terminal=Control+Shift+Return
color-theme-toggle=Control+Shift+Tab

[colors-dark]
alpha=0.8
foreground=e5e5e5
background=000000
regular0=000000 # black
regular1=cd0000 # red
regular2=00cd00 # green
regular3=cdcd00 # yellow
regular4=0000ee # blue
#regular4=1e90ff # blue
regular5=cd00cd # magenta
regular6=00cdcd # cyan
regular7=e5e5e5 # white
bright0=7f7f7f  # bright black
bright1=ff0000  # bright red
bright2=00ff00  # bright green
bright3=ffff00  # bright yellow
bright4=5c5cff  # bright blue
#bright4=63b8ff  # bright blue
bright5=ff00ff  # bright magenta
bright6=00ffff  # bright cyan
bright7=ffffff  # bright white

[colors-light]
alpha=0.8
foreground=1a1a1a
background=ffffff
regular0=000000 # black
regular1=cd0000 # red
regular2=00cd00 # green
regular3=cdcd00 # yellow
regular4=0000ee # blue
#regular4=1e90ff # blue
regular5=cd00cd # magenta
regular6=00cdcd # cyan
regular7=e5e5e5 # white
bright0=7f7f7f  # bright black
bright1=ff0000  # bright red
bright2=00ff00  # bright green
bright3=ffff00  # bright yellow
bright4=5c5cff  # bright blue
#bright4=63b8ff  # bright blue
bright5=ff00ff  # bright magenta
bright6=00ffff  # bright cyan
bright7=ffffff  # bright white
