# -*- conf -*-

include=~/.config/foot/colorscheme.ini

font=GoMono Nerd Font Mono:size=14
font-size-adjustment=1
box-drawings-uses-font-glyphs=no
dpi-aware=no

initial-window-size-chars=80x24
pad=4x4
resize-delay-ms=0

bold-text-in-bright=no
word-delimiters=,│`|:"'()[]{}<>
selection-target=primary

login-shell=no

[bell]
urgent=no
notify=no
visual=no

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

[cursor]
style=block
blink=no

[key-bindings]
spawn-terminal=Control+Shift+Return

# vim: ft=dosini
